services:
  database:
    image: 'postgres:16-alpine'
    container_name: chronos-db
    environment:
      - POSTGRES_DB=chronos_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d chronos_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: chronos-api
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/chronos_db
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: chronos-ui
    ports:
      - '5173:80' # Mapeamos el puerto 80 del contenedor al 5173 local
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend

volumes:
  postgres_data: