services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: chronos-link-db
    environment:
      - 'POSTGRES_DB=chronos_db'
      - 'POSTGRES_PASSWORD=dev_password'
      - 'POSTGRES_USER=dev_user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d chronos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: