# URL: jdbc:postgresql://[host]:[puerto]/[nombre_db]
spring.datasource.url=jdbc:postgresql://localhost:5432/chronos_db
spring.datasource.username=dev_user
spring.datasource.password=dev_password

# Estrategia de JPA: 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.docker.compose.file=backend/compose.yaml